<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickpriority</name>
   <tag></tag>
   <elementGuidId>63954b21-28d1-4057-84c2-a75ac69baadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;a05122020&quot;]/div/div/div/div/div/div/table/tbody[1]/tr[1]/td[2]/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
